- app/assets/javascripts/admin/customers.coffee
- app/assets/javascripts/admin/home.coffee
- app/assets/stylesheets/admin/customers.scss
- app/assets/stylesheets/admin/home.scss
- app/controllers/admin/customers_controller.rb
- app/controllers/admin/home_controller.rb
- app/helpers/admin/customers_helper.rb
- app/helpers/admin/home_helper.rb
- app/views/admin/customers/index.html.slim
- app/views/admin/home/index.html.slim
- app/views/admin/home/top.html.slim
- config/routes.rb
- db/seeds.rb
- test/controllers/admin/customers_controller_test.rb
- test/controllers/admin/home_controller_test.rb
> [admin] 顧客一覧画面の作成

- Gemfile
- Gemfile.lock
> bootstrapのアップグレード

- app/controllers/admin/customers_controller.rb
- app/views/admin/customers/edit.html.slim
- app/views/admin/customers/show.html.slim
- config/routes.rb
- いじったところ
- admin/customers#edit
- admin/customers#update
> [admin] 顧客退会機能の実装

- app/views/admin/customers/index.html.slim
> admin/customers/index.html.slim 編集リンクの追加

- app/models/address.rb
- app/models/cart_item.rb
- app/models/customer.rb
- app/models/disc.rb
- app/models/favorite.rb
- app/models/genre.rb
- app/models/item.rb
- app/models/label.rb
- app/models/order.rb
- app/models/order_item.rb
- app/models/resigned_customer.rb
- app/models/singer.rb
- app/models/song.rb
全て完了しましたがスペルミスなどあるかもしれないのであったらissue立てて直してください
close #15
> アソシエーションの設定

- app/views/admin/customers/index.html.slim
- app/views/admin/customers/show.html.slim
> #7 [admin] 顧客退会機能の修正

- merge.sh
> shellスクリプト書いた

- app/controllers/application_controller.rb
- app/views/customers/top.html.slim
> サインアップとログイン後の遷移先をグッズ一覧にしました！

- Gemfile.lock
- app/assets/stylesheets/application.scss
- app/assets/stylesheets/cart_items.scss
- app/views/cart_items/index.html.slim
> cart_items index modified

- app/assets/javascripts/searches.coffee
- app/assets/stylesheets/searches.scss
- app/controllers/application_controller.rb
- app/controllers/searches_controller.rb
- app/helpers/searches_helper.rb
- app/views/layouts/application.html.slim
- app/views/searches/index.html.slim
- config/routes.rb
- db/migrate/20190715105844_devise_create_admins.rb
- test/controllers/searches_controller_test.rb
#27 
商品だけでなく、レーベル、ジャンル、アーティストも出るようにしました
検索方法は普通にLIKEの部分一致しか使ってません
何も検索していないときは全ての商品を表示しています
リンクは整形に任せたいと思います
> #27 検索機能の実装

- app/controllers/admin/customers_controller.rb
- app/controllers/admin/discs_controller.rb
- app/controllers/admin/genres_controller.rb
- app/controllers/admin/home_controller.rb
- app/controllers/admin/item_kinds_controller.rb
- app/controllers/admin/items_controller.rb
- app/controllers/admin/labels_controller.rb
- app/controllers/admin/orders_controller.rb
- app/controllers/admin/resigned_customers_controller.rb
- app/controllers/admin/singers_controller.rb
- app/controllers/admin/songs_controller.rb
- app/controllers/cart_items_controller.rb
- app/controllers/customers_controller.rb
- app/controllers/orders_controller.rb
- config/routes.rb
- customerのルーティングを修正
- ログイン後でしかアクセスできないページを分ける
- customerに使っていないルーティング,アクションがあったので`edit,update,destroy,show,about`だけにした
- 該当コントローラーに`before_action :authenticate_customer!`を書いた
- `customer,cart_item,order`に書いた
- 該当コントローラーに`before_action :authenticate_admin!`を書いた
- adminの全て
- 今回で`customer/about`が死んでしまったので #100
> 一般公開とログイン公開に分ける

- app/controllers/application_controller.rb
- db/migrate/20190715101122_devise_create_customers.rb
- db/migrate/20190717020523_add_resigned_to_customers.rb
- db/migrate/20190722074138_remove_del_from_items.rb
- db/schema.rb
- ログイン機能が #101  の修正でぶっ壊れたのでそれの修正
-
-
> ログインできないのを修正

- app/controllers/customers_controller.rb
- app/views/customers/edit.html.slim
- ユーザー編集機能の追加
- 普通に実装した
- deviseの仕様上勝手にログアウトするがまあセキュリティー的に正しそう
- close #107
> ユーザー編集機能の追加

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/customers.scss
- app/views/customers/show.html.slim
- app/views/layouts/application.html.slim
> customer show

- Gemfile
- Gemfile.lock
- app/assets/javascripts/application.js
- app/controllers/orders_controller.rb
- app/views/orders/new.html.slim
- いいねきのうのjsが動いてないのでその修正
- turbolinksのgemを削除した
-
> jsが効かないバグを修正

- app/assets/javascripts/application.js
- app/assets/stylesheets/customers.scss
- app/controllers/orders_controller.rb
- app/views/customers/show.html.slim
-モーダルを閉じるときにモーダルの外をクリックする仕様に変更
-モーダルの中の良いねした曲をクリックすると詳細ページに遷移
-customer 詳細ページ整形
-
-他ページでモーダル実装するときはapplication.jsの記述はしてあるのでcustomer_showのクラス名参考にしてください
close #110
> mypage -customer-show

- app/views/orders/new.html.slim
-  カートに商品がないと購入できないようにした
- ユーザーのカートアイテムの個数が0買おうかで条件分岐した
- ActiveRecordは中に何もなくてもfalseじゃないのか 🤔
- close #118
> カートに商品がない状態でも購入できてしまうバグを修正

- app/assets/javascripts/application.js
- app/assets/stylesheets/items.scss
- app/views/customers/show.html.slim
- app/views/items/show.html.slim
-item_show実装
-曲一覧をtabの切り替えで実装
-エラーが出てたのでjsの記述を直接slimファイルで書いた(この前作ったcustomer_showのjsの記述もapplication.jsからcustomer_showのslimファイルに移動したのでコンフリクト起こったらすいません)
-
-
> finish item_show

- app/controllers/admin/discs_controller.rb
- app/controllers/admin/songs_controller.rb
- app/views/admin/customers/index.html.slim
- app/views/admin/customers/show.html.slim
- app/views/admin/home/index.html.slim
- app/views/admin/item_kinds/index.html.slim
- app/views/admin/items/edit.html.slim
- app/views/admin/items/index.html.slim
- app/views/admin/items/new.html.slim
- app/views/admin/items/show.html.slim
- app/views/admin/orders/index.html.slim
- app/views/customers/about.html.slim
- app/views/customers/edit.html.slim
- app/views/customers/show.html.slim
- app/views/items/show.html.slim
- app/views/layouts/application.html.slim
- app/views/orders/new.html.slim
- ユーザー一覧画面の整形
- application.html.slimで前バグってたところをリファクタリングしました
- ヘッダーをadminでログイン時はユーザー一覧、商品一覧、受注、歌手関連、ログアウトのボタンにしました
-
- close #2 close #99
> [admin] ユーザー一覧画面の整形

- app/assets/stylesheets/items.scss
- app/views/admin/items/edit.html.slim
- app/views/admin/items/index.html.slim
- [admin] 商品一覧の整形 商品作成、編集の整形
-
- 少し見やすくした程度だけど管理者側なのでまあいいかなと
- close #42 close #44
> [admin] 商品一覧の整形 商品作成、編集の整形

- app/views/admin/items/edit.html.slim
- app/views/admin/items/show.html.slim
- 商品詳細ページの整形
- 商品編集ページの整形
-
- 葉狩くんのを99.99%パクりました
> [admin] 商品詳細ページの整形 

- app/views/items/show.html.slim
- 商品詳細ページにログインしていない状態で行くとエラーが出るのを修正
- customerの情報を要求される行をifで回避した
-
> バグの修正 close #127

- app/assets/stylesheets/orders.scss
- app/controllers/orders_controller.rb
- app/views/admin/customers/index.html.slim
- app/views/admin/customers/show.html.slim
- app/views/admin/orders/index.html.slim
- app/views/admin/orders/show.html.slim
- app/views/customers/show.html.slim
- config/routes.rb
- 管理者の受注一覧と詳細を整形した
- 管理者のユーザー詳細を整形した
- 退会ユーザにはこのユーザーは退会済みですと表示されるようにした(一覧、詳細)
- エンドユーザーと同じようにshowページを整形した
- close #129
> 管理者の受注関係を整形

- app/assets/stylesheets/cart_items.scss
- app/assets/stylesheets/customers.scss
- app/assets/stylesheets/orders.scss
- app/views/cart_items/index.html.slim
- app/views/items/show.html.slim
- app/views/orders/new.html.slim
-issue37の編集ページの作業ではないです
-カート商品一覧や購入確認画面でカート内合計と各商品小計額が出ていなかったので付け足しました
-あとちょこちょこ前担当したページにcss関連追加してます
-
-この後issue37ちゃんとやります。
> Issue37kai

- app/assets/stylesheets/customers.scss
- app/views/customers/edit.html.slim
-customer_editページ整形
-
-close #37
> finish customer_edit

- app/views/items/show.html.slim
- 
-　ifで商品ストックがない場合カートに追加できないようにした
-
> close #136 #137
